name: RMCP Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    
    - name: Install R packages
      run: |
        R -e "install.packages(c('jsonlite', 'plm', 'lmtest', 'sandwich', 'AER', 'dplyr', 'forecast', 'vars', 'urca', 'tseries', 'nortest', 'car', 'rpart', 'randomForest', 'ggplot2', 'gridExtra', 'tidyr', 'rlang', 'readxl'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click jsonschema pytest pytest-asyncio
    
    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v
    
    - name: Test new tools specifically
      run: |
        python tests/unit/test_new_tools.py

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    
    - name: Install R packages
      run: |
        R -e "install.packages(c('jsonlite', 'plm', 'lmtest', 'sandwich', 'AER', 'dplyr', 'forecast', 'vars', 'urca', 'tseries', 'nortest', 'car', 'rpart', 'randomForest', 'ggplot2', 'gridExtra', 'tidyr', 'rlang', 'readxl'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click jsonschema pytest pytest-asyncio
    
    - name: Run MCP interface tests
      run: |
        python tests/integration/test_mcp_interface.py
    
    - name: Run direct capabilities tests
      run: |
        python tests/integration/test_direct_capabilities.py
    
    - name: Run new features integration tests
      run: |
        python tests/integration/test_new_features_integration.py

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: integration-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    
    - name: Install R packages
      run: |
        R -e "install.packages(c('jsonlite', 'plm', 'lmtest', 'sandwich', 'AER', 'dplyr', 'forecast', 'vars', 'urca', 'tseries', 'nortest', 'car', 'rpart', 'randomForest', 'ggplot2', 'gridExtra', 'tidyr', 'rlang', 'readxl'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click jsonschema pytest pytest-asyncio
    
    - name: Run realistic scenarios
      run: |
        python tests/e2e/realistic_scenarios.py
    
    - name: Run Claude Desktop scenarios
      run: |
        python tests/e2e/test_claude_desktop_scenarios.py
    
    - name: Run Docker simulation tests
      run: |
        python tests/e2e/test_docker_simulation.py

  tool-count-verification:
    name: Verify Tool Count
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    
    - name: Install R packages
      run: |
        R -e "install.packages(c('jsonlite', 'plm', 'lmtest', 'sandwich', 'AER', 'dplyr'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click jsonschema
    
    - name: Verify tool registration count
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        from rmcp.core.server import create_server
        from rmcp.cli import _register_builtin_tools
        server = create_server()
        _register_builtin_tools(server)
        import asyncio
        async def count():
            ctx = server.create_context('test', 'tools/list')
            result = await server.tools.list_tools(ctx)
            count = len(result['tools'])
            print(f'Registered tools: {count}')
            assert count >= 40, f'Expected at least 40 tools, got {count}'
            print('✅ Tool count verification passed')
        asyncio.run(count())
        "

  # New feature verification
  new-features-smoke-test:
    name: New Features Smoke Test
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
    
    - name: Install R packages
      run: |
        R -e "install.packages(c('jsonlite', 'dplyr'), repos='https://cran.rstudio.com/')"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install click jsonschema
    
    - name: Test formula builder
      run: |
        python -c "
        import sys, asyncio, json
        sys.path.insert(0, '.')
        from rmcp.core.server import create_server
        from rmcp.registries.tools import register_tool_functions
        from rmcp.tools.formula_builder import build_formula
        from rmcp.tools.helpers import suggest_fix, load_example
        
        async def test():
            server = create_server()
            register_tool_functions(server.tools, build_formula, suggest_fix, load_example)
            
            # Test formula building
            req = {'jsonrpc': '2.0', 'id': 1, 'method': 'tools/call', 'params': {'name': 'build_formula', 'arguments': {'description': 'predict sales from marketing'}}}
            resp = await server.handle_request(req)
            result = json.loads(resp['result']['content'][0]['text'])
            assert 'formula' in result
            print(f'✅ Formula builder: {result[\"formula\"]}')
            
            # Test error recovery
            req = {'jsonrpc': '2.0', 'id': 2, 'method': 'tools/call', 'params': {'name': 'suggest_fix', 'arguments': {'error_message': 'there is no package called \"forecast\"'}}}
            resp = await server.handle_request(req)
            result = json.loads(resp['result']['content'][0]['text'])
            assert result['error_type'] == 'missing_package'
            print(f'✅ Error recovery: {result[\"error_type\"]}')
            
            # Test example datasets
            req = {'jsonrpc': '2.0', 'id': 3, 'method': 'tools/call', 'params': {'name': 'load_example', 'arguments': {'dataset_name': 'sales', 'size': 'small'}}}
            resp = await server.handle_request(req)
            result = json.loads(resp['result']['content'][0]['text'])
            assert 'data' in result
            print(f'✅ Example datasets: {result[\"metadata\"][\"rows\"]} rows loaded')
            
            print('🎊 All new features working!')
        
        asyncio.run(test())
        "

  documentation-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README mentions new features
      run: |
        grep -q "40 statistical tools" README.md || (echo "❌ README doesn't mention 40 tools" && exit 1)
        grep -q "Natural Language" README.md || (echo "❌ README doesn't mention natural language features" && exit 1)
        grep -q "Error Recovery" README.md || (echo "❌ README doesn't mention error recovery" && exit 1)
        echo "✅ Documentation check passed"
    
    - name: Check version consistency
      run: |
        grep -q "Version 0.3.5" README.md || (echo "❌ README version not updated" && exit 1)
        grep -q "version.*0.3.5" pyproject.toml || (echo "❌ pyproject.toml version not updated" && exit 1)
        echo "✅ Version consistency check passed"